/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BAccordion: typeof import('bootstrap-vue-next')['BAccordion']
    BAccordionItem: typeof import('bootstrap-vue-next')['BAccordionItem']
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardFooter: typeof import('bootstrap-vue-next')['BCardFooter']
    BCardHeader: typeof import('bootstrap-vue-next')['BCardHeader']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']

    BIconPatchCheck: typeof import('bootstrap-vue-next')['BIconPatchCheck']

    BListGroup: typeof import('bootstrap-vue-next')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next')['BListGroupItem']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    BPopover: typeof import('bootstrap-vue-next')['BPopover']
    BProgress: typeof import('bootstrap-vue-next')['BProgress']
    BProgressBar: typeof import('bootstrap-vue-next')['BProgressBar']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BThead: typeof import('bootstrap-vue-next')['BThead']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next')['vBToggle']
  }
}
